### ISSUE TITLE
add impact load balancing

### ISSUE THREAD

**Issue by dwcarder** [dwcarder/draft-cc-v6ops-wlcg-flow-label-marking#10]
From Brian C.:

As well as the impact on ECMP/LAG (where you might add a reference to
RFC 6438), could you also mention the impact on server load balancing
(RFC 7098)? The real issue here is that with only 5 random bits, the
probability of two very large flows hashing to the same path or server
is higher than we'd like. But since the WLCG flows are *all* very large,
this presumably doesn't matter so much in your use case?

----------

we could add that reference, and also see about clarifying typical size and duration of our flows?

**Comment by dwcarder** [comment]
From Tom H:
Regardless of the algorithm,
if we only have five bits of entropy to work with then there will be a
lot of collisions for flows between the same two endpoints. This could
create load imbalances in ECMP. I think this would practically only be
a problem for something like tunnels where many flow are encapsulate
over a tunnel and the only entropy is the flow label

**Comment by timchown** [comment]
A "lot" is 1 in 32 sharing the same entropy bits, on average?

Isn't there guidance somewhere that says do not just use the flow label for hashing?
