### ISSUE TITLE
Describe nature of WLCG traffic

### ISSUE THREAD

**Issue by timchown** [dwcarder/draft-cc-v6ops-wlcg-flow-label-marking#13]
Someone queried the infrastructure over which WLCG traffic flows.
This is related to the load balancing, I think.

We could briefly describe traffic will go over one of
LHCOPN
LHCONE
General R&E IP networks

And describe that while WLCG transfers may aggregate to many 10s of Gbit/s or even 100G+, the constituent flows are usually not that large, a few hundred Mbit/s or very low Gbit/s.  Large 5-10G+ flows are unusual.  I can ask for some data on this.

**Comment by dwcarder** [comment]
I took a swing at this in commit 3d7386ca5b39c5b821722bb73a424fc0f25ce63e for which I forgot to do in a branch, sigh.
