### ISSUE TITLE
add a reference for firefly

### ISSUE THREAD

**Issue by dwcarder** [dwcarder/draft-cc-v6ops-wlcg-flow-label-marking#8]
Suggestion from Brian C. is that we add a reference.  I am not sure offhand what we have published we want to link to.  The recent CHEP talk?

**Comment by dwcarder** [comment]
other idea from Tim is to drop this section and purely focus on v6.

**Comment by timchown** [comment]
I think we should mention flow marking with fireflies, as opposed to the packet marking this draft covers, but no more than that.  So just a reference.

Tim

On 30 Jun 2023, at 19:59, Dale W. Carder ***@***.***> wrote:



other idea from Tim is to drop this section and purely focus on v6.

**Comment by marian-babik** [comment]
For now we only have CHEP talk (https://indico.jlab.org/event/459/contributions/11321/). Deadline for CHEP paper was postponed to September and it will likely take some time before we have an actual reference.

**Comment by marian-babik** [comment]
There was also TNC talk (https://tnc23.geant.org/sessions/#s269)

**Comment by timchown** [comment]
Either would do.
